services:

  _defaults:
    public: false
    autowire: true
    bind:
      OxidEsales\Eshop\Core\Session: '@=service("OxidEsales\\EVatModule\\Core\\Registry").getSession()'
      OxidEsales\Eshop\Core\UtilsObject: '@=service("OxidEsales\\EVatModule\\Core\\Registry").getUtilsObject()'
      OxidEsales\Eshop\Core\UtilsView: '@=service("OxidEsales\\EVatModule\\Core\\Registry").getUtilsView()'

  OxidEsales\EVatModule\Core\Registry:
    class: OxidEsales\Eshop\Core\Registry
    public: true

  OxidEsales\EVatModule\Model\Evidence\Item\Evidence:
    abstract: true
  OxidEsales\EVatModule\Model\Evidence\:
    resource: 'src/Model/Evidence'
    public: true
  OxidEsales\EVatModule\Model\DbGateway\:
    resource: 'src/Model/DbGateway'
    public: true

  OxidEsales\EVatModule\Service\:
    resource: 'src/Service'
    public: true

#todo: Move to Services?
  OxidEsales\EVatModule\Model\ArticleVATGroupsList:
    public: true
  OxidEsales\EVatModule\Model\IncorrectVATArticlesMessageFormatter:
    public: true
  OxidEsales\EVatModule\Model\CategoryArticlesUpdater:
    public: true
  OxidEsales\EVatModule\Model\CategoryVATGroupsList:
    public: true
  OxidEsales\EVatModule\Model\CountryVATGroup:
    public: true
  OxidEsales\EVatModule\Model\CountryVATGroupsList:
    public: true
  OxidEsales\EVatModule\Model\BasketVATValidator:
    public: true
  OxidEsales\EVatModule\Model\OrderEvidenceList:
    public: true
  OxidEsales\EVatModule\Model\OrderArticleChecker:
    public: true
  OxidEsales\EVatModule\Model\User:
    public: true

  OxidEsales\EVatModule\Core\Cache\Generic\Cache:
    class: '\OxidEsales\Eshop\Core\Cache\Generic\Cache'
    factory: ['@OxidEsales\EVatModule\Service\CacheFactory', 'getCacheIfAvailable']

  OxidEsales\EVatModule\Model\GroupArticleCacheInvalidator:
    arguments:
      $oCacheBackend: '@?OxidEsales\EVatModule\Core\Cache\Generic\Cache'
    public: true