install:
  cache:
    prepared_shop: false
  composer:
    transform: |
      {
        "config": {
          "allow-plugins": {
            "oxid-esales/oxideshop-unified-namespace-generator": true,
            "oxid-esales/oxideshop-composer-plugin": true
          }
        },
        "require": {
            "oxid-esales/oxideshop-ce": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/twig-admin-theme": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/apex-theme": "{{ .Data.install.composer.dev_ref }}",
            "oxid-esales/evat-module": "{{ .Data.install.composer.ref_name }}"
        },
        "autoload-dev": {
          "psr-4": {
            "OxidEsales\\EshopCommunity\\Tests\\": "./vendor/oxid-esales/oxideshop-ce/tests"
          }
        }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:theme:activate apex
    vendor/bin/oe-console oe:module:activate oevattbe

runscript:
  matrix:
    script: |
      [
        "evat:tests-unit",
        "evat:tests-integration",
      ]
  evat:
    path: 'vendor/oxid-esales/evat-module'

sonarcloud:
  matrix:
    testplan: '["-"]'
  project_key: 'OXID-eSales_vat_tbe_services'
  project_name: 'oxid-esales/evat-module'
  organization: 'oxid-esales'
  strip_path: '/var/www/vendor/oxid-esales/evat-module/'
  parameters: >
    -Dsonar.language=php
    -Dsonar.scm.provider=git
    -Dsonar.sources=src
    -Dsonar.tests=tests

finish:
  slack_title: 'Module evat-module ({{ .Github.RefName }}) on {{ .Github.Repository }} by {{ .Github.Actor }}'
