name: Development

on:
  workflow_call:
    inputs:
      php:
        required: true
        type: string
      mysql:
        required: true
        type: string
      template_engine:
        type: string
        default: 'both'
      module_codecept_test_group:
        type: string
        default: 'oevattbe'
      report_sonarcloud:
        type: boolean
        default: false
      report_slack:
        type: boolean
        default: true

  workflow_dispatch:
    inputs:
      php:
        description: 'PHP version'
        required: true
        default: '8.0'
        type: choice
        options:
          - '8.0'
          - '8.1'
      mysql:
        description: 'MySQL version'
        required: true
        default: '5.7.37'
        type: choice
        options:
          - '5.7.37'
          - '8.0'
env:
  PACKAGE_NAME: 'oxid-esales/evat-module'
  MODULE_PATH: 'oe/oevattbe'
  MODULE_ID: 'oevattbe'
  SONARCLOUD_ORGANIZATION: 'oxid-esales'
  SONARCLOUD_PROJECT_KEY: 'OXID-eSales_module-vat-t-be'

jobs:
  install_shop_with_module:
    runs-on: ubuntu-latest
    steps:
      - name: Print run parameters
        run: |
          echo "Running job with:\
            PHP version: ${{ inputs.php }}\
            MySQL version: ${{ inputs.mysql }}\
            Template engine: ${{ inputs.template_engine }}\
            Tests group: ${{ inputs.module_codecept_test_group }}\
            Trigger event: ${{ github.event_name }}"

      - name: Cleanup workspace
        run: |
          ls -la ./
          sudo rm -rf ./* || true
          sudo rm -rf ./.??* || true
          ls -la ./

      - name: Clone testing environment
        run: git clone https://github.com/OXID-eSales/docker-eshop-sdk.git .

      - name: Clone the shop
        run: git clone --depth 1 https://github.com/OXID-eSales/oxideshop_ce.git --branch b-7.0.x --single-branch source

      - name: Cache current installation
        uses: actions/cache@v3
        with:
          path: |
            ./*
          key: installation-${{ github.sha }}-${{ join(inputs.*, '-') }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Prepare container configuration
        run: |
          make setup
          make addbasicservices
          make file=services/selenium-chrome.yml addservice
          perl -pi\
            -e 's#PHP_VERSION=.*#PHP_VERSION=${{ inputs.php }}#g;'\
            -e "s#MYSQL_VERSION=.*#MYSQL_VERSION=${{ inputs.mysql }}#g;"\
            .env

          perl -pi\
            -e 's#display_errors =.*#display_errors = false#g;'\
            -e 's#error_reporting = .*#error_reporting = E_ALL ^ E_WARNING ^ E_DEPRECATED#g;'\
            -e 'print "xdebug.max_nesting_level=1000\nxdebug.mode=coverage\n\n"'\
            containers/php/custom.ini

          perl -pi\
            -e 's#/var/www/#/var/www/source/#g;'\
            containers/httpd/project.conf

      - name: Prepare shop configuration
        run: |
          cp source/source/config.inc.php.dist source/source/config.inc.php
          sed -i "1s+^+SetEnvIf Authorization "\(.*\)" HTTP_AUTHORIZATION=\$1\n\n+" source/source/.htaccess
          sed -i -e 's/<dbHost>/mysql/'\
                 -e 's/<dbUser>/root/'\
                 -e 's/<dbName>/example/'\
                 -e 's/<dbPwd>/root/'\
                 -e 's/<dbPort>/3306/'\
                 -e 's/<sShopURL>/http:\/\/localhost.local\//'\
                 -e 's/<sShopDir>/\/var\/www\/source\//'\
                 -e 's/<sCompileDir>/\/var\/www\/source\/tmp\//'\
              source/source/config.inc.php

      - name: Checkout current module
        uses: actions/checkout@v3
        with:
          path: source/test-module

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Start containers
        run: |
          make up
          sleep 5

      - name: Install EE
        run: |
          docker-compose exec -T php composer config github-protocols https
          docker-compose exec -T php composer config -g github-oauth.github.com ${{ secrets.GH_CI_JENKINS_TOKEN }}
          docker-compose exec -T php composer config repositories.oxid-esales/oxideshop-pe git https://github.com/OXID-eSales/oxideshop_pe.git
          docker-compose exec -T php composer config repositories.oxid-esales/oxideshop-ee git https://github.com/OXID-eSales/oxideshop_ee.git
          docker-compose exec -T php composer require oxid-esales/oxideshop-pe:dev-b-7.0.x --no-update
          docker-compose exec -T php composer require oxid-esales/oxideshop-ee:dev-b-7.0.x --no-plugins --no-scripts
          docker-compose exec -T php composer require symfony/dotenv:^5.1 --no-update
          docker-compose exec -T php composer config repositories.oxid-esales/oxideshop-demodata-ee git https://github.com/OXID-eSales/oxideshop_demodata_ee.git
          docker-compose exec -T php composer require oxid-esales/oxideshop-demodata-ee:dev-master --no-update

      - name: Install module
        run: |
          docker-compose exec -T \
            php composer config repositories.${{ env.PACKAGE_NAME }} \
            --json '{"type":"path", "url":"./test-module", "options": {"symlink": true}}'
          docker-compose exec -T \
            php composer require ${{ env.PACKAGE_NAME }}:* --no-interaction --no-update

      - name: Install dependencies and reset shop
        run: |
          docker-compose exec -T php composer update --no-interaction
          docker-compose exec -T php bin/oe-console oe:database:reset \
            --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
          docker-compose exec -T php bin/oe-console oe:module:activate ${{ env.MODULE_ID }}

      - name: Show docker log
        if: always()
        run: |
          docker ps
          docker-compose logs

      - name: Stop containers
        if: always()
        run: |
          docker-compose down
          sleep 2

      - name: Cleanup Docker
        if: always()
        run: |
          c=$(docker ps -q) && [[ $c ]] && docker kill $c
          docker system prune --force

      - name: Upload configuration artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Configs-${{ inputs.php }}-${{ inputs.mysql }}-${{ inputs.template_engine }}
          path: |
            docker-compose.yml
            source/composer.json
            source/composer.lock
            source/source/config.inc.php

  unit_tests:
    needs: [ install_shop_with_module ]
    runs-on: ubuntu-latest
    steps:
      - name: Load current installation from cache
        uses: actions/cache@v3
        with:
          fail-on-cache-miss: true
          path: |
            ./*
          key: installation-${{ github.sha }}-${{ join(inputs.*, '-') }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            installation-${{ github.sha }}-${{ join(inputs.*, '-') }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Start containers
        run: |
          make up
          sleep 2

      - name: Run tests
        run: |
          docker-compose exec -T \
            -e PARTIAL_MODULE_PATHS=${{ env.MODULE_PATH }} \
            -e ACTIVATE_ALL_MODULES=1 \
            -e RUN_TESTS_FOR_SHOP=0 \
            -e RUN_TESTS_FOR_MODULES=0 \
            -e XDEBUG_MODE=coverage \
            -e ADDITIONAL_TEST_PATHS='/var/www/vendor/${{ env.PACKAGE_NAME }}/tests' \
            php php vendor/bin/runtests \
              --coverage-clover=/var/www/coverage.xml \
              --coverage-text \
              --log-junit=/var/www/phpunit.xml \
              AllTestsUnit

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestsLog-${{ matrix.php }}
          path: |
            source/coverage.xml
            source/phpunit.xml

  integration_tests:
    needs: [ install_shop_with_module ]
    runs-on: ubuntu-latest
    steps:
      - name: Load current installation from cache
        uses: actions/cache@v3
        with:
          fail-on-cache-miss: true
          path: |
            ./*
          key: installation-${{ github.sha }}-${{ join(inputs.*, '-') }}-${{ github.run_number }}-${{ github.run_attempt }}
          restore-keys: |
            installation-${{ github.sha }}-${{ join(inputs.*, '-') }}-${{ github.run_number }}-${{ github.run_attempt }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Start containers
        run: |
          make up
          sleep 2

      - name: Run tests
        run: |
          docker-compose exec -T \
            -e XDEBUG_MODE=coverage \
            php php vendor/bin/phpunit \
              -c /var/www/vendor/${{ env.PACKAGE_NAME }}/tests/phpunit.xml \
              --testsuite=Integration \
              --bootstrap=/var/www/source/bootstrap.php \
              --coverage-text \
              --coverage-php=/var/www/integration.cov

      - name: Upload log artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ModuleIntegrationTestsLog-${{ inputs.php }}-${{ inputs.mysql }}-${{ inputs.template_engine }}
          path: |
            source/integration.cov
            source/source/log/oxideshop.log
            data/php/logs/error_log.txt

      - name: Stop containers
        if: always()
        run: |
          docker-compose down
          sleep 2

      - name: Cleanup Docker
        if: always()
        run: |
          c=$(docker ps -q) && [[ $c ]] && docker kill $c
          docker system prune --force
