name: Trigger

on:
  pull_request:
  push:
    branches:
      - 'b-7.0.x*'

jobs:
  p80m57both:
    name: 'Php-8.0-Mysql-5.7'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.0'
      mysql: '5.7.37'
      report_sonarcloud: true

  p81m80both:
    name: 'Php-8.1-Mysql-8.0'
    uses: ./.github/workflows/development.yml
    secrets: inherit
    with:
      php: '8.1'
      mysql: '8.0'

  php_81_ee:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger EE workflow and wait for results
        uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: oxid-esales
          repo: module-workflows
          github_user: ${{ secrets.CI_USER }}
          github_token: ${{ secrets.GH_CI_JENKINS_TOKEN }}
          workflow_file_name: evat_workflow.yml
          ref: "master"
          client_payload: "{\"php\": \"8.1\", \"mysql\": \"8.0\", \"ref\": \"${{ github.ref_name }}\"}"